name: mock-playwright-test

on:
  workflow_run:
    workflows: [mock-deploy-test]
    types: [completed]
    branches: [master]
  workflow_dispatch:

jobs:
  mock-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sleep
        run: sleep 3

      - name: Run a one-line script
        run: echo Successfully ran mock-playwright! # success動作確認用
        # run: hoge # failure動作確認用

      # - name: Update GitHub Actions status (success)
      #   if: ${{ success() }}
      #   # ref: https://docs.github.com/en/rest/commits/statuses#create-a-commit-status
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
      #     --header 'authorization: Bearer ${{ github.token }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "state": "success",
      #       "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
      #       "context": "mock-playwright"
      #     }'
      # - name: Update GitHub Actions status (failure)
      #   if: ${{ failure() }}
      #   # ref: https://docs.github.com/en/rest/commits/statuses#create-a-commit-status
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
      #     --header 'authorization: Bearer ${{ github.token }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "state": "failure",
      #       "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
      #       "context": "mock-playwright"
      #     }'
